/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import model.Sorteio;

/**
 *
 * @author Biel
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    public static ArrayList<Sorteio> listaSorteios = new ArrayList<Sorteio>();
    Sorteio sorteio;
    
    FrmMegaSena megaSena;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        for (int i = 0; i <= 4999; i++)
        {
            int random1 = geraDezena();
            
            int random2 = geraDezena();
            if (random1 == random2)
                random2 = geraDezena();
            
            int random3 = geraDezena();
            if (random3 == random2 || random3 == random1)
                random3 = geraDezena();
            
            int random4 = geraDezena();
            if (random4 == random3 || random3 == random2 || random4 == random1)
                random4 = geraDezena();
            
            int random5 = geraDezena();
            if (random5 == random4 || random5 == random3 || random5 == random2 || random5 == random1)
                random5 = geraDezena();
            
            int random6 = geraDezena();
            if (random6 == random5 || random6 == random4 || random6 == random3 || random6 == random2 || random6 == random1)
                random6 = geraDezena();
            
            
            sorteio = new Sorteio();
            sorteio.setNumeroJogo(i+1);
            sorteio.setDezena1(random1);
            sorteio.setDezena2(random2);
            sorteio.setDezena3(random3);
            sorteio.setDezena4(random4);
            sorteio.setDezena5(random5);
            sorteio.setDezena6(random6);
            listaSorteios.add(sorteio);
        }
        sorteio = new Sorteio();
        sorteio.setNumeroJogo(5000);
        sorteio.setDezena1(10);
        sorteio.setDezena2(15);
        sorteio.setDezena3(20);
        sorteio.setDezena4(25);
        sorteio.setDezena5(30);
        sorteio.setDezena6(35);
        listaSorteios.add(sorteio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnMega = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prova 2");
        setExtendedState(MAXIMIZED_BOTH);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Sorteio");

        btnMega.setText("Mega Sena");
        btnMega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegaActionPerformed(evt);
            }
        });
        jMenu1.add(btnMega);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegaActionPerformed
        megaSena = new FrmMegaSena();
        desktop.add(megaSena);
        megaSena.setVisible(true);
    }//GEN-LAST:event_btnMegaActionPerformed

    /**
     * @param args the command line arguments
     */
    public int geraDezena()
    {
        Random r = new Random();
        return r.nextInt(60)+1;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnMega;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
