/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Produto;
/**
 *
 * @author Biel
 */
public class FrmProduto extends javax.swing.JInternalFrame {

    ArrayList<Produto> produtos = new ArrayList<Produto>();
    Produto p;
    /**
     * Creates new form FrmProd
     */
    
    public FrmProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDescr = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        txtEstMin = new javax.swing.JTextField();
        btnCad = new javax.swing.JToggleButton();
        btnAlterar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        btnConsultar = new javax.swing.JToggleButton();
        btnPrimeiro = new javax.swing.JToggleButton();
        btnAnterior = new javax.swing.JToggleButton();
        btnAvancar = new javax.swing.JToggleButton();
        btnUltimo = new javax.swing.JToggleButton();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(410, 350));
        setPreferredSize(new java.awt.Dimension(410, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cód:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Descrição:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setText("Estoque:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setText("Estoque minimo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 280, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 280, -1));
        getContentPane().add(txtDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 280, -1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 280, -1));
        getContentPane().add(txtEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 280, -1));
        getContentPane().add(txtEstMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 280, -1));

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        getContentPane().add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        btnExcluir.setText("Excluir");
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        btnPrimeiro.setText("<<");
        getContentPane().add(btnPrimeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnAnterior.setText("<");
        getContentPane().add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        btnAvancar.setText(">");
        getContentPane().add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        btnUltimo.setText(">>");
        getContentPane().add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        p = new Produto();
        
        p.setCod(Integer.parseInt(txtCod.getText()));
        p.setNome(txtNome.getText());
        p.setDescri(txtDescr.getText());
        p.setValor(Double.parseDouble(txtValor.getText()));
        p.setEstoque(Integer.parseInt(txtEstoque.getText()));
        p.setEstMin(Integer.parseInt(txtEstMin.getText())); 
        
        this.produtos.add(p);
        limpadinha();
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        for (Produto p : this.produtos)
        {
            int codd = Integer.parseInt(txtCod.getText());
            if(p.getCod() == codd)
            {
                txtNome.setText(p.getNome());
                txtValor.setText(p.getValor().toString());
                txtEstMin.setText(p.getEstMin() + "");
                txtDescr.setText(p.getDescri());
                txtEstoque.setText(p.getEstoque() + "");
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        txtDescr.setText(txtNome.getText());
// JOptionPane(null, txtCod.toString(), txtNome.toString(), JOptionPane.QUESTION_MESSAGE);
        //System.console().printf("EE");
        //System.console().printf(txtCod.toString());
        //System.console().printf(txtNome.toString());
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void limpadinha() {
        txtCod.setText("");
        txtNome.setText("");
        txtValor.setText("");
        txtEstMin.setText("");
        txtDescr.setText("");
        txtEstoque.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JToggleButton btnAnterior;
    private javax.swing.JToggleButton btnAvancar;
    private javax.swing.JToggleButton btnCad;
    private javax.swing.JToggleButton btnConsultar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnPrimeiro;
    private javax.swing.JToggleButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDescr;
    private javax.swing.JTextField txtEstMin;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
